title: "Du-Lab"
description: "personal description"
url: "https://bravedu01.github.io"
baseurl: ""
repository: "bravedu01/bravedu01.github.io"
locale: "en-US"

author:
  name: "Yong Du"
  email: "duyongfnp@gmail.com"
  location: "Earth"
  github: "bravedu01"
  googlescholar: "https://scholar.google.com/citations?hl=en&user=EtUtLTkAAAAJ&view_op=list_works&sortby=pubdate"
  pubmed: "https://www.ncbi.nlm.nih.gov/pubmed/?term=yong+du"
  orcid: "https://orcid.org/0000-0003-2986-6249"

collections:
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/

include:
  - _pages
  - files

exclude:
  - Dockerfile
  - Gemfile
  - node_modules
  - README.md
  - LICENSE
  - "*.sublime-*"
  - vendor

markdown: kramdown

navigation:
  - title: "Home"
    url: /
  - title: "CV"
    url: /cv/
  - title: "Publications"
    url: https://scholar.google.com/citations?hl=en&user=EtUtLTkAAAAJ&view_op=list_works&sortby=pubdate
  - title: "Teaching"
    url: /teaching/

highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
