title: "Du Lab"
description: "Tumor immunology and autoimmunity"
url: "https://bravedu01.github.io"
baseurl: ""
repository: "bravedu01/bravedu01.github.io"
locale: "en-US"

author:
  name: "Yong Du"
  email: "duyongfnp@gmail.com"
  github: "bravedu01"
  googlescholar: "https://scholar.google.com/citations?user=EtUtLTkAAAAJ&hl=en"
  pubmed: "https://www.ncbi.nlm.nih.gov/pubmed/?term=yong+du"
  orcid: "https://orcid.org/0000-0003-2986-6249"

navigation:
  - title: "Home"
    url: /
  - title: "Team"
    url: /teams/
  - title: "CV"
    url: /cv/
  - title: "Publications"
    url: /publication/
  - title: "Funding"
    url: /funding/
  - title: "Contact"
    url: /contact/

# 指定自定义页面文件夹
include:
  - _pages

# 使用的 Jekyll 主题
remote_theme: academicpages/academicpages.github.io

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
